Fix: AppleClang16 issues (#27)
* Problem: fork_union won't compile on macos/clang16

**First problem**:

```c++
 #if defined(__linux__) && defined(__GLIBC__) && __GLIBC_PREREQ(2, 30)
```

results in:

```
error: function-like macro '__GLIBC_PREREQ' is not define
```

**Second problem**:

```
error: too many template arguments for class template 'allocation_result'
operator std::allocation_result<pointer_type, size_type>() const noexcept {
      |                   ^                               ~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/c++/v1/__memory/allocate_at_least.h:24:8: note: template is declared here
   23 | template <class _Pointer>
      | ~~~~~~~~~~~~~~~~~~~~~~~~~
   24 | struct allocation_result {
```

(it appears it doesn't correctly follow the specification?)

Solution: make it compilable

For the **first problem**, reorganize the directives to avoid them being
used on macOS.

For the **second problem**, let the compiler infer the return type.

Since `std::allocation_result` is a C++23 thing, I've augmented tests to
run on C++23 as well.

* Auto-enable NUMA for Linux with GLibC 2.30+ support

---------

Co-authored-by: Ash Vardanian <1983160+ashvardanian@users.noreply.github.com>